{% set name = "pyqstrat" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyqstrat-{{ version }}.tar.gz
  sha256: fb3493bc96a6db437e28313117d579f88acd0cabdcdaa9fd05e17df6a5cc4f22

build:
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('pybind11') }}
    - python
    - pandas
    - statsmodels
    - ipython
    - sortedcontainers
    - h5py
    - ipywidgets
    - plotly >=4.10
    - libzip
    - cython
    - python-dateutil
    - types-python-dateutil
    - traitlets
    - pandas_market_calendars
    - pyyaml

test:
  imports:
    - pyqstrat
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/abbass2/pyqstrat/
  summary: fast / extensible library for backtesting quantitative strategies
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - abbass2
